const categories = {
  "greetings": {
    "en": "Greetings",
    "tr": "Selamlaşma",
    "alm": "Grüße",
    "fr": "Salutations",
    "it": "Saluti",
    "es": "Saludos",
    "ja": "ご挨拶",
    "ar": "تحيات",
    "el": "Χαιρετίσματα"
  },
  "social": {
    "en": "Social Life",
    "tr": "Sosyal Hayat",
    "alm": "Soziales Leben",
    "fr": "Vie Sociale",
    "it": "Vita Sociale",
    "es": "Vida Social",
    "ja": "社会生活",
    "ar": "الحياة الاجتماعية",
    "el": "Κοινωνική Ζωή"
  },
  "common": {
    "en": "Common Phrases",
    "tr": "Genel İfadeler",
    "alm": "Allgemeine Ausdrücke",
    "fr": "Phrases Courantes",
    "it": "Frasi Comuni",
    "es": "Frases Comunes",
    "ja": "よく使われるフレーズ",
    "ar": "عبارات شائعة",
    "el": "Κοινές φράσεις"
  },
  "communication": {
    "en": "Communication",
    "tr": "İletişim",
    "alm": "Kommunikation",
    "fr": "Communication",
    "it": "Comunicazione",
    "es": "Comunicación",
    "ja": "コミュニケーション",
    "ar": "تواصل",
    "el": "Ανακοίνωση"
  },
  "time": {
    "en": "Time & Date",
    "tr": "Zaman & Tarih",
    "alm": "Zeit & Datum",
    "fr": "Heure et Date",
    "it": "Ora e Data",
    "es": "Hora y Fecha",
    "ja": "時刻と日付",
    "ar": "الوقت والتاريخ",
    "el": "Ώρα & Ημερομηνία"
  },
  "opinions": {
    "en": "Opinions",
    "tr": "Fikirler",
    "alm": "Meinungen",
    "fr": "Des Opinions",
    "it": "Opinioni",
    "es": "Opiniones",
    "ja": "意見",
    "ar": "آراء",
    "el": "Απόψεις"
  },
  "travel": {
    "en": "Travel",
    "tr": "Seyahat",
    "alm": "Reisen",
    "fr": "Voyage",
    "it": "Viaggio",
    "es": "Viaje",
    "ja": "旅行",
    "ar": "يسافر",
    "el": "Ταξίδι"
  },
  "transportation": {
    "en": "Transportation",
    "tr": "Ulaşım",
    "alm": "Transport",
    "fr": "Transport",
    "it": "Trasporti",
    "es": "Transporte",
    "ja": "交通機関",
    "ar": "مواصلات",
    "el": "Μεταφορά"
  },
  "public_transport": {
    "en": "Public Transport",
    "tr": "Toplu Taşıma",
    "alm": "Öffentlicher Verkehr",
    "fr": "Transports Publics",
    "it": "Trasporto Pubblico",
    "es": "Transporte Público",
    "ja": "公共交通機関",
    "ar": "النقل العام",
    "el": "Μέσα Μαζικής Μεταφοράς"
  },
  "directions": {
    "en": "Directions",
    "tr": "Yön Tarifi",
    "alm": "Wegbeschreibung",
    "fr": "Directions",
    "it": "Indicazioni",
    "es": "Direcciones",
    "ja": "方向",
    "ar": "الاتجاهات",
    "el": "Οδηγίες"
  },
  "shopping": {
    "en": "Shopping",
    "tr": "Alışveriş",
    "alm": "Einkaufen",
    "fr": "Achats",
    "it": "Shopping",
    "es": "Compras",
    "ja": "買い物",
    "ar": "التسوق",
    "el": "Ψώνια"
  },
  "dining": {
    "en": "Eating & Drinking",
    "tr": "Yeme & İçme",
    "alm": "Essen & Trinken",
    "fr": "Manger et Boire",
    "it": "Mangiare e Bere",
    "es": "Comer y Beber",
    "ja": "飲食",
    "ar": "الأكل والشرب",
    "el": "Φαγητό & Ποτό"
  },
  "accommodation": {
    "en": "Accommodation",
    "tr": "Konaklama",
    "alm": "Unterkunft",
    "fr": "Logement",
    "it": "Alloggio",
    "es": "Alojamiento",
    "ja": "宿泊施設",
    "ar": "إقامة",
    "el": "Κατάλυμα"
  },
  "technology": {
    "en": "Technology",
    "tr": "Teknoloji",
    "alm": "Technologie",
    "fr": "Technologie",
    "it": "Tecnologia",
    "es": "Tecnología",
    "ja": "テクノロジー",
    "ar": "تكنولوجيا",
    "el": "Τεχνολογία"
  },
  "airport": {
    "en": "Airport",
    "tr": "Havalimanı",
    "alm": "Flughafen",
    "fr": "Aéroport",
    "it": "Aeroporto",
    "es": "Aeropuerto",
    "ja": "空港",
    "ar": "مطار",
    "el": "Αεροδρόμιο"
  },
  "health": {
    "en": "Health",
    "tr": "Sağlık",
    "alm": "Gesundheit",
    "fr": "Santé",
    "it": "Salute",
    "es": "Salud",
    "ja": "健康",
    "ar": "صحة",
    "el": "Υγεία"
  },
  "emergency": {
    "en": "Emergency",
    "tr": "Acil Durum",
    "alm": "Notfall",
    "fr": "Urgence",
    "it": "Emergenza",
    "es": "Emergencia",
    "ja": "緊急",
    "ar": "طارئ",
    "el": "Επείγον"
  },
  "rental": {
    "en": "Car Rental",
    "tr": "Araç Kiralama",
    "alm": "Autovermietung",
    "fr": "Location de Voiture",
    "it": "Noleggio Auto",
    "es": "Alquiler de Coches",
    "ja": "レンタカー",
    "ar": "تأجير سيارات",
    "el": "Ενοικίαση αυτοκινήτων"
  },
  "activity_winter": {
    "en": "Winter Sports",
    "tr": "Kış Sporları & Kayak",
    "alm": "Wintersport",
    "fr": "Sports d'Hiver",
    "it": "Sport Invernali",
    "es": "Deportes de Invierno",
    "ja": "ウィンタースポーツ",
    "ar": "الرياضات الشتوية",
    "el": "Χειμερινά σπόρ"
  },
  "activity_summer": {
    "en": "Summer & Beach",
    "tr": "Yaz & Plaj",
    "alm": "Sommer & Strand",
    "fr": "Été et Plage",
    "it": "Estate e Spiaggia",
    "es": "Verano y Playa",
    "ja": "サマー＆ビーチ",
    "ar": "الصيف والشاطئ",
    "el": "Καλοκαίρι & Παραλία"
  },
  "sightseeing": {
    "en": "Sightseeing",
    "tr": "Tarihi Yerler & Gezi",
    "alm": "Besichtigung",
    "fr": "Tourisme",
    "it": "Turismo",
    "es": "Turismo",
    "ja": "観光",
    "ar": "مشاهدة المعالم السياحية",
    "el": "Περιοδεία εις αξιοθέατα μέρη"
  },
  "activities": {
    "en": "Activities",
    "tr": "Aktiviteler & Eğlence",
    "alm": "Aktivitäten",
    "fr": "Activités",
    "it": "Attività",
    "es": "Actividades",
    "ja": "活動内容",
    "ar": "أنشطة",
    "el": "Δραστηριότητες"
  },
  "official": {
    "en": "Official Procedures",
    "tr": "Resmi İşlemler",
    "alm": "Offizielle Verfahren",
    "fr": "Procédures Officielles",
    "it": "Procedure Ufficiali",
    "es": "Trámites Oficiales",
    "ja": "正式な手続き",
    "ar": "الإجراءات الرسمية",
    "el": "Επίσημες Διαδικασίες"
  },
  "beauty": {
    "en": "Hairdresser & Beauty",
    "tr": "Kuaför & Bakım",
    "alm": "Friseur & Schönheit",
    "fr": "Coiffeur et Beauté",
    "it": "Parrucchiere e Bellezza",
    "es": "Peluquería y Belleza",
    "ja": "美容師＆美容師",
    "ar": "تصفيف الشعر والتجميل",
    "el": "Κομμωτήριο & Ομορφιά"
  },
  "health_chronic": {
    "en": "Chronic Diseases",
    "tr": "Kronik Hastalıklar",
    "alm": "Chronische Krankheiten",
    "fr": "Maladies Chroniques",
    "it": "Malattie Croniche",
    "es": "Enfermedades Crónicas",
    "ja": "慢性疾患",
    "ar": "الأمراض المزمنة",
    "el": "Χρόνια Νοσήματα"
  },
  "health_pet": {
    "en": "Pet Health (Vet)",
    "tr": "Evcil Hayvan & Veteriner",
    "alm": "Tiergesundheit",
    "fr": "Santé Animale",
    "it": "Salute degli Animali",
    "es": "Salud de Mascotas",
    "ja": "ペットの健康 (獣医)",
    "ar": "صحة الحيوانات الأليفة (الطبيب البيطري)",
    "el": "Υγεία κατοικίδιων ζώων (Κτηνίατρος)"
  },
  "legal": {
    "en": "Legal & Police",
    "tr": "Hukuk, Polis & Konsolosluk",
    "alm": "Recht & Polizei",
    "fr": "Juridique et Police",
    "it": "Legale e Polizia",
    "es": "Legal y Policía",
    "ja": "法務と警察",
    "ar": "القانونية والشرطة",
    "el": "Νομική & Αστυνομία"
  },
  "vehicle_tech": {
    "en": "Vehicle Problems",
    "tr": "Araç Arıza & Teknik",
    "alm": "Fahrzeugprobleme",
    "fr": "Problèmes de Véhicule",
    "it": "Problemi del Veicolo",
    "es": "Problemas del Vehículo",
    "ja": "車両の問題",
    "ar": "مشاكل المركبات",
    "el": "Προβλήματα οχημάτων"
  },
  "accommodation_problems": {
    "en": "Accommodation Issues",
    "tr": "Konaklama Sorunları",
    "alm": "Unterkunftsprobleme",
    "fr": "Problèmes de Logement",
    "it": "Problemi di Alloggio",
    "es": "Problemas de Alojamiento",
    "ja": "宿泊施設の問題",
    "ar": "قضايا السكن",
    "el": "Θέματα Διαμονής"
  },
  "diet_special": {
    "en": "Diet & Allergies",
    "tr": "Diyet, Helal & Alerji",
    "alm": "Diät & Allergien",
    "fr": "Régime et Allergies",
    "it": "Dieta e Allergie",
    "es": "Dieta y Alergias",
    "ja": "食事とアレルギー",
    "ar": "النظام الغذائي والحساسية",
    "el": "Διατροφή & Αλλεργίες"
  },
  "transport_alt": {
    "en": "Alternative Transport",
    "tr": "Alternatif Ulaşım (Scooter/Uber)",
    "alm": "Alternativer Transport",
    "fr": "Transport Alternatif",
    "it": "Trasporto Alternativo",
    "es": "Transporte Alternativo",
    "ja": "代替輸送",
    "ar": "النقل البديل",
    "el": "Εναλλακτικές Μεταφορές"
  },
  "navigation_safety": {
    "en": "Navigation & Safety",
    "tr": "Yön & Güvenlik",
    "alm": "Navigation & Sicherheit",
    "fr": "Navigation et Sécurité",
    "it": "Navigazione e Sicurezza",
    "es": "Navegación y Seguridad",
    "ja": "ナビゲーションと安全性",
    "ar": "الملاحة والسلامة",
    "el": "Πλοήγηση & Ασφάλεια"
  },
  "finance_bargain": {
    "en": "Bargaining & Prices",
    "tr": "Pazarlık & Fiyatlar",
    "alm": "Verhandeln & Preise",
    "fr": "Négociation et Prix",
    "it": "Contrattazione e Prezzi",
    "es": "Regateo y Precios",
    "ja": "交渉と価格",
    "ar": "المساومة والأسعار",
    "el": "Διαπραγματεύσεις & Τιμές"
  },
  "tech_advanced": {
    "en": "Tech & Connection",
    "tr": "Teknoloji & Bağlantı",
    "alm": "Technik & Verbindung",
    "fr": "Technologie et Connexion",
    "it": "Tecnologia e Connessione",
    "es": "Tecnología y Conexión",
    "ja": "テクノロジーとコネクション",
    "ar": "التكنولوجيا والاتصال",
    "el": "Τεχνολογία & Σύνδεση"
  },
  "logistics": {
    "en": "Luggage & Logistics",
    "tr": "Bagaj & Kargo",
    "alm": "Gepäck & Logistik",
    "fr": "Bagages et Logistique",
    "it": "Bagagli e Logistica",
    "es": "Equipaje y Logística",
    "ja": "荷物と物流",
    "ar": "الأمتعة والخدمات اللوجستية",
    "el": "Αποσκευές & Logistics"
  },
  "culture": {
    "en": "Culture & Rules",
    "tr": "Kültür & Kurallar",
    "alm": "Kultur & Regeln",
    "fr": "Culture et Règles",
    "it": "Cultura e Regole",
    "es": "Cultura y Reglas",
    "ja": "文化とルール",
    "ar": "الثقافة والقواعد",
    "el": "Πολιτισμός & Κανόνες"
  },
  "psychology": {
    "en": "Psychological Support",
    "tr": "Psikolojik Destek",
    "alm": "Psychologische Unterstützung",
    "fr": "Soutien Psychologique",
    "it": "Supporto Psicologico",
    "es": "Apoyo Psicológico",
    "ja": "心理的サポート",
    "ar": "الدعم النفسي",
    "el": "Ψυχολογική Υποστήριξη"
  },
  "daily_needs": {
    "en": "Daily Needs",
    "tr": "Günlük İhtiyaçlar",
    "alm": "Täglicher Bedarf",
    "fr": "Besoins Quotidiens",
    "it": "Bisogni Quotidiani",
    "es": "Necesidades Diarias",
    "ja": "日常の必需品",
    "ar": "الاحتياجات اليومية",
    "el": "Καθημερινές Ανάγκες"
  },
  "religion": {
    "en": "Religious Needs",
    "tr": "Dini İhtiyaçlar & İbadet",
    "alm": "Religiöse Bedürfnisse",
    "fr": "Besoins Religieux",
    "it": "Bisogni Religiosi",
    "es": "Necesidades Religiosas",
    "ja": "宗教上の必要性",
    "ar": "الاحتياجات الدينية",
    "el": "Θρησκευτικές Ανάγκες"
  },
  "accommodation_repair": {
    "en": "Room/Hotel Repairs",
    "tr": "Oda & Otel Arızaları",
    "alm": "Zimmerreparaturen",
    "fr": "Réparations de Chambre",
    "it": "Riparazioni della Camera",
    "es": "Reparaciones de Habitaciones",
    "ja": "部屋/ホテルの修理",
    "ar": "إصلاحات الغرفة/الفندق",
    "el": "Επισκευές δωματίων/ξενοδοχείων"
  },
  "rental_maintenance": {
    "en": "Home Rental & Maintenance",
    "tr": "Ev Kiralama & Tamirat",
    "alm": "Vermietung & Wartung",
    "fr": "Location et Entretien",
    "it": "Affitto e Manutenzione",
    "es": "Alquiler y Mantenimiento",
    "ja": "住宅のレンタルとメンテナンス",
    "ar": "تأجير وصيانة المنازل",
    "el": "Ενοικίαση & Συντήρηση Κατοικίας"
  },
  "rental_housing": {
    "en": "House & Room Rental",
    "tr": "Ev & Oda Kiralama",
    "alm": "Haus & Zimmervermietung",
    "fr": "Location Maison & Chambre",
    "it": "Affitto Casa & Stanza",
    "es": "Alquiler de Casa y Habitación",
    "ja": "ハウス＆ルームレンタル",
    "ar": "تأجير المنازل والغرف",
    "el": "Ενοικίαση Κατοικίας & Δωματίου"
  },
  "rental_marine": {
    "en": "Boat & Yacht Rental",
    "tr": "Tekne & Yat Kiralama",
    "alm": "Boots & Yachtverleih",
    "fr": "Location Bateau & Yacht",
    "it": "Noleggio Barche & Yacht",
    "es": "Alquiler de Barcos y Yates",
    "ja": "ボートとヨットのレンタル",
    "ar": "تأجير القوارب واليخوت",
    "el": "Ενοικίαση σκαφών και γιοτ"
  },
  "rental_problems": {
    "en": "Rental Problems (Car/Gen)",
    "tr": "Kiralama Sorunları & Hasar",
    "alm": "Mietprobleme",
    "fr": "Problèmes de Location",
    "it": "Problemi di Noleggio",
    "es": "Problemas de Alquiler",
    "ja": "レンタルの問題 (車/発電機)",
    "ar": "مشاكل الإيجار (السيارة/الجنرال)",
    "el": "Προβλήματα ενοικίασης (Car/Gen)"
  },
  "housing_problems": {
    "en": "House Damage & Issues",
    "tr": "Ev Hasarı & Sorunlar",
    "alm": "Hausschäden",
    "fr": "Dommages au Logement",
    "it": "Danni alla Casa",
    "es": "Daños en la Vivienda",
    "ja": "住宅の損傷と問題",
    "ar": "أضرار المنزل وقضاياه",
    "el": "Ζημιές & Ζητήματα σπιτιού"
  },
  "marine_problems": {
    "en": "Boat/Sea Emergencies",
    "tr": "Deniz & Tekne Acil Durum",
    "alm": "Bootsnotfälle",
    "fr": "Urgences en Mer",
    "it": "Emergenze in Mare",
    "es": "Emergencias Marítimas",
    "ja": "ボート/海の緊急事態",
    "ar": "حالات الطوارئ على متن القارب/البحر",
    "el": "Έκτακτη ανάγκη για σκάφος/θαλάσσια"
  },
  "education_campus": {
    "en": "Education & Campus Life",
    "tr": "Eğitim & Kampüs",
    "alm": "Bildung & Campus",
    "fr": "Éducation et Campus",
    "it": "Istruzione e Campus",
    "es": "Educación y Campus",
    "ja": "教育とキャンパスライフ",
    "ar": "التعليم والحياة في الحرم الجامعي",
    "el": "Εκπαίδευση & Ζωή στην Πανεπιστημιούπολη"
  },
  "library": {
    "en": "Library",
    "tr": "Kütüphane",
    "alm": "Bibliothek",
    "fr": "Bibliothèque",
    "it": "Biblioteca",
    "es": "Biblioteca",
    "ja": "図書館",
    "ar": "مكتبة",
    "el": "Βιβλιοθήκη"
  },
  "events_culture": {
    "en": "Events & Culture",
    "tr": "Etkinlik & Kültür Sanat",
    "alm": "Veranstaltungen & Kultur",
    "fr": "Événements et Culture",
    "it": "Eventi e Cultura",
    "es": "Eventos y Cultura",
    "ja": "イベントと文化",
    "ar": "الأحداث والثقافة",
    "el": "Εκδηλώσεις & Πολιτισμός"
  },
  "rules_regulations": {
    "en": "Rules & Regulations",
    "tr": "Kurallar & Yasaklar",
    "alm": "Regeln & Vorschriften",
    "fr": "Règles et Règlements",
    "it": "Regole e Regolamenti",
    "es": "Reglas y Regulaciones",
    "ja": "規則と規制",
    "ar": "القواعد واللوائح",
    "el": "Κανόνες & Κανονισμοί"
  },
  "business_work": {
    "en": "Work & Business",
    "tr": "İş Hayatı & Ofis",
    "alm": "Arbeit & Geschäft",
    "fr": "Travail et Affaires",
    "it": "Lavoro e Affari",
    "es": "Trabajo y Negocios",
    "ja": "仕事とビジネス",
    "ar": "العمل والأعمال",
    "el": "Εργασία & Επιχειρήσεις"
  },
  "banking": {
    "en": "Banking & Cards",
    "tr": "Banka & Kart İşlemleri",
    "alm": "Bankwesen & Karten",
    "fr": "Banque et Cartes",
    "it": "Banche e Carte",
    "es": "Banca y Tarjetas",
    "ja": "銀行とカード",
    "ar": "الخدمات المصرفية والبطاقات",
    "el": "Τραπεζικές εργασίες και κάρτες"
  },
  "gastronomy": {
    "en": "Local Food & Gastronomy",
    "tr": "Yerel Lezzetler & Gastronomi",
    "alm": "Lokales Essen & Gastronomie",
    "fr": "Cuisine Locale et Gastronomie",
    "it": "Cibo Locale e Gastronomia",
    "es": "Comida Local y Gastronomía",
    "ja": "地元の食べ物と美食",
    "ar": "الطعام المحلي وفن الطهو",
    "el": "Τοπικό Φαγητό & Γαστρονομία"
  },
  "health_tests": {
    "en": "Medical Tests (MRI/Blood)",
    "tr": "Tahlil, MR & Röntgen",
    "alm": "Medizinische Tests",
    "fr": "Tests Médicaux",
    "it": "Test Medici",
    "es": "Pruebas Médicas",
    "ja": "医療検査（MRI/血液）",
    "ar": "الفحوصات الطبية (التصوير بالرنين المغناطيسي/الدم)",
    "el": "Ιατρικές εξετάσεις (MRI/αίματος)"
  },
  "health_optical": {
    "en": "Optical & Prosthetics",
    "tr": "Gözlük, Lens & Protez",
    "alm": "Optik & Prothetik",
    "fr": "Optique et Prothèses",
    "it": "Ottica e Protesi",
    "es": "Óptica y Prótesis",
    "ja": "光学および補綴物",
    "ar": "البصرية والأطراف الصناعية",
    "el": "Οπτικά & Προσθετικά"
  },
  "consumer_rights": {
    "en": "Warranty & Service",
    "tr": "Garanti, Servis & İade",
    "alm": "Garantie & Service",
    "fr": "Garantie et Service",
    "it": "Garanzia e Assistenza",
    "es": "Garantía y Servicio",
    "ja": "保証とサービス",
    "ar": "الضمان والخدمة",
    "el": "Εγγύηση & Service"
  },
  "logistics_delivery": {
    "en": "Post & Cargo",
    "tr": "Kargo & Posta İşlemleri",
    "alm": "Post & Fracht",
    "fr": "Poste et Fret",
    "it": "Posta e Merce",
    "es": "Correo y Carga",
    "ja": "郵便と貨物",
    "ar": "البريد والشحن",
    "el": "Post & Cargo"
  },
  "banking_ops": {
    "en": "Banking Operations",
    "tr": "Bankacılık İşlemleri",
    "alm": "Bankgeschäfte",
    "fr": "Opérations Bancaires",
    "it": "Operazioni Bancarie",
    "es": "Operaciones Bancarias",
    "ja": "銀行業務",
    "ar": "العمليات المصرفية",
    "el": "Τραπεζικές εργασίες"
  },
  "social_flirting": {
    "en": "Dating & Flirting",
    "tr": "Buluşma & Flört",
    "alm": "Dating & Flirten",
    "fr": "Rencontres et Flirt",
    "it": "Incontri e Flirt",
    "es": "Citas y Flirteo",
    "ja": "デート＆浮気",
    "ar": "المواعدة والمغازلة",
    "el": "Ραντεβού και φλερτ"
  },
  "career_interview": {
    "en": "Job Interview",
    "tr": "İş Görüşmesi",
    "alm": "Vorstellungsgespräch",
    "fr": "Entretien d'Embauche",
    "it": "Colloquio di Lavoro",
    "es": "Entrevista de Trabajo",
    "ja": "就職面接",
    "ar": "مقابلة وظيفية",
    "el": "Συνέντευξη για εργασία"
  },
  "contract_meeting": {
    "en": "Business Contracts",
    "tr": "Sözleşme & Anlaşma",
    "alm": "Geschäftsverträge",
    "fr": "Contrats Commerciaux",
    "it": "Contratti Commerciali",
    "es": "Contratos Comerciales",
    "ja": "ビジネス契約",
    "ar": "العقود التجارية",
    "el": "Επιχειρηματικές Συμβάσεις"
  },
  "career_pro": {
    "en": "Professional Labor Rights",
    "tr": "Profesyonel Çalışma Hakları",
    "alm": "Professionelle Arbeitsrechte",
    "fr": "Droits du Travail Professionnels",
    "it": "Diritti del Lavoro Professionali",
    "es": "Derechos Laborales Profesionales",
    "ja": "専門労働者の権利",
    "ar": "حقوق العمل المهنية",
    "el": "Επαγγελματικά Εργατικά Δικαιώματα"
  },
  "reactions": {
    "en": "Quick Reactions & Feedback",
    "tr": "Hızlı Tepkiler & Geri Bildirim",
    "alm": "Schnelle Reaktionen",
    "fr": "Réactions Rapides",
    "it": "Reazioni Rapide",
    "es": "Reacciones Rápidas",
    "ja": "素早い反応とフィードバック",
    "ar": "ردود الفعل السريعة وردود الفعل",
    "el": "Γρήγορες αντιδράσεις και σχόλια"
  },
  "culture_religion": {
    "en": "Culture & Religion",
    "tr": "Kültür & Din",
    "alm": "Kultur & Religion",
    "fr": "Culture et Religion",
    "it": "Cultura e Religione",
    "es": "Cultura y Religión",
    "ja": "文化と宗教",
    "ar": "الثقافة والدين",
    "el": "Πολιτισμός & Θρησκεία"
  },
  "sports_outdoor": {
    "en": "Sports & Outdoor",
    "tr": "Spor & Doğa Sporları",
    "alm": "Sport & Outdoor",
    "fr": "Sports et Nature",
    "it": "Sport e Outdoor",
    "es": "Deportes y Aire Libre",
    "ja": "スポーツ＆アウトドア",
    "ar": "الرياضة والخارجية",
    "el": "Αθλητισμός & Υπαίθριος"
  },
  "hobby_art": {
    "en": "Hobbies & Arts",
    "tr": "Hobi & Sanat",
    "alm": "Hobbies & Kunst",
    "fr": "Loisirs et Arts",
    "it": "Hobby e Arte",
    "es": "Aficiones y Artes",
    "ja": "趣味と芸術",
    "ar": "الهوايات والفنون",
    "el": "Χόμπι & Τέχνες"
  },
  "bureaucracy_finance": {
    "en": "Finance & Bureaucracy",
    "tr": "Finans & Bürokrasi",
    "alm": "Finanzen & Bürokratie",
    "fr": "Finance et Bureaucratie",
    "it": "Finanza e Burocrazia",
    "es": "Finanzas y Burocracia",
    "ja": "財務と官僚制",
    "ar": "المالية والبيروقراطية",
    "el": "Οικονομικά & Γραφειοκρατία"
  },
  "pet_care": {
    "en": "Pet Care",
    "tr": "Evcil Hayvan Bakımı",
    "alm": "Haustierpflege",
    "fr": "Soins des Animaux",
    "it": "Cura degli Animali",
    "es": "Cuidado de Mascotas",
    "ja": "ペットケア",
    "ar": "رعاية الحيوانات الأليفة",
    "el": "Φροντίδα κατοικίδιων ζώων"
  },
  "tech_master": {
    "en": "Technical & Maintenance",
    "tr": "Teknik, Arıza & Bakım",
    "alm": "Technik & Wartung",
    "fr": "Technique et Maintenance",
    "it": "Tecnica e Manutenzione",
    "es": "Técnica y Mantenimiento",
    "ja": "技術とメンテナンス",
    "ar": "التقنية والصيانة",
    "el": "Τεχνική & Συντήρηση"
  },
  "legal_pro": {
    "en": "Advanced Legal Affairs",
    "tr": "İleri Düzey Hukuk & Resmî İşler",
    "alm": "Fortgeschrittene Rechtsangelegenheiten",
    "fr": "Affaires Juridiques Avancées",
    "it": "Affari Legali Avanzati",
    "es": "Asuntos Legales Avanzados",
    "ja": "高度な法務",
    "ar": "الشؤون القانونية المتقدمة",
    "el": "Προηγμένες Νομικές Υποθέσεις"
  },
  "social_deep": {
    "en": "Deep Social Interaction",
    "tr": "Derin Sosyal İlişkiler",
    "alm": "Tiefe soziale Interaktion",
    "fr": "Interaction Sociale Profonde",
    "it": "Interazione Sociale Profonda",
    "es": "Interacción Social Profunda",
    "ja": "深い社会的交流",
    "ar": "التفاعل الاجتماعي العميق",
    "el": "Βαθιά κοινωνική αλληλεπίδραση"
  },
  "family_kids": {
    "en": "Family & Child Care",
    "tr": "Aile & Çocuk Bakımı",
    "alm": "Familie & Kinderbetreuung",
    "fr": "Famille et Garde d'Enfants",
    "it": "Famiglia e Cura dei Bambini",
    "es": "Familia y Cuidado de Niños",
    "ja": "家族と育児",
    "ar": "رعاية الأسرة والطفل",
    "el": "Οικογένεια & Παιδική Φροντίδα"
  },
  "shopping_pro": {
    "en": "Advanced Shopping & Returns",
    "tr": "İleri Düzey Alışveriş & İade",
    "alm": "Einkaufen & Rückgabe",
    "fr": "Achats et Retours",
    "it": "Acquisti e Resi",
    "es": "Compras y Devoluciones",
    "ja": "高度なショッピングと返品",
    "ar": "التسوق والإرجاع المتقدم",
    "el": "Προηγμένες αγορές και επιστροφές"
  },
  "shopping_bargain": {
    "en": "Bargaining & Markets",
    "tr": "Pazarlık & Yerel Pazarlar",
    "alm": "Handeln & Märkte",
    "fr": "Négociation et Marchés",
    "it": "Contrattazione e Mercati",
    "es": "Regateo y Mercados",
    "ja": "交渉と市場",
    "ar": "المساومة والأسواق",
    "el": "Διαπραγματεύσεις & Αγορές"
  },
  "shopping_pharmacy": {
    "en": "Pharmacy & Health Products",
    "tr": "Eczane & Sağlık Ürünleri",
    "alm": "Apotheke & Gesundheitsprodukte",
    "fr": "Pharmacie et Produits de Santé",
    "it": "Farmacia e Prodotti per la Salute",
    "es": "Farmacia y Productos de Salud",
    "ja": "薬局および健康製品",
    "ar": "الصيدلة والمنتجات الصحية",
    "el": "Φαρμακευτικά & Προϊόντα Υγείας"
  },
  "shopping_tech": {
    "en": "Technology & Electronics",
    "tr": "Teknoloji & Elektronik",
    "alm": "Technik & Elektronik",
    "fr": "Technologie et Électronique",
    "it": "Tecnologia ed Elettronica",
    "es": "Tecnología y Electrónica",
    "ja": "テクノロジーとエレクトロニクス",
    "ar": "التكنولوجيا والإلكترونيات",
    "el": "Τεχνολογία & Ηλεκτρονικά"
  },
  "shopping_cosmetic": {
    "en": "Cosmetics & Beauty",
    "tr": "Kozmetik & Güzellik",
    "alm": "Kosmetik & Schönheit",
    "fr": "Cosmétiques et Beauté",
    "it": "Cosmetici e Bellezza",
    "es": "Cosméticos y Belleza",
    "ja": "化粧品と美容",
    "ar": "مستحضرات التجميل والجمال",
    "el": "Καλλυντικά & Ομορφιά"
  },
  "dining_pro": {
    "en": "Gourmet Dining & Chef's Selection",
    "tr": "Gurme Yemek & Şefin Seçimi",
    "alm": "Gourmet-Essen & Chef-Auswahl",
    "fr": "Dîner Gastronomique et Sélection du Chef",
    "it": "Cena Gourmet e Selezione dello Chef",
    "es": "Cena Gourmet y Selección del Chef",
    "ja": "グルメダイニングとシェフのセレクション",
    "ar": "تناول الطعام الذواقة واختيار الشيف",
    "el": "Gourmet Dining & Chef's Selection"
  },
  "quick_access": {
    "en": "Emergency & Quick Actions",
    "tr": "Acil Durum & Hızlı Erişim",
    "alm": "Notfall & Schnellzugriff",
    "fr": "Urgence et Accès Rapide",
    "it": "Emergenza e Accesso Rapido",
    "es": "Emergencia y Acceso Rápido",
    "ja": "緊急時と迅速な対応",
    "ar": "الإجراءات الطارئة والسريعة",
    "el": "Έκτακτες & Γρήγορες Ενέργειες"
  },
  "feelings": {
    "en": "Feelings & Emotions",
    "tr": "Duygular & Hisler",
    "alm": "Gefühle & Emotionen",
    "fr": "Sentiments et Émotions",
    "it": "Sentimenti ed Emozioni",
    "es": "Sentimientos y Emociones",
    "ja": "感情と感情",
    "ar": "المشاعر والعواطف",
    "el": "Συναισθήματα & Συναισθήματα"
  },
  "airport_pro": {
    "en": "Airport & Flight Details",
    "tr": "Havaalanı & Uçuş Detayları",
    "alm": "Flughafen & Flugdetails",
    "fr": "Aéroport et Détails du Vol",
    "it": "Aeroporto e Dettagli del Volo",
    "es": "Aeropuerto y Detalles del Vuelo",
    "ja": "空港とフライトの詳細",
    "ar": "تفاصيل المطار والطيران",
    "el": "Λεπτομέρειες αεροδρομίου & πτήσης"
  },
  "traffic_driving": {
    "en": "Traffic & Driving",
    "tr": "Trafik & Sürüş Kuralları",
    "alm": "Verkehr & Fahren",
    "fr": "Trafic et Conduite",
    "it": "Traffico e Guida",
    "es": "Tráfico y Conducción",
    "ja": "交通と運転",
    "ar": "حركة المرور والقيادة",
    "el": "Κυκλοφορία & Οδήγηση"
  },
   games: {
      en: "Games & Fun",
      tr: "Oyun & Eğlence",
      alm: "Spiele & Spaß",
      fr: "Jeux et Divertissement",
      it: "Giochi e Divertimento",
      es: "Juegos y Diversión",
      jp: "ゲームと娯楽 (Gēmu to goraku)",
      ru: "Игры и развлечения (Igry i razvlecheniya)"
  }
}